//
//  EvielasLibrary.m
//  E-vielas
//
//  Created by Aleksandrs Muravjovs on 22/05/2017.
//  Copyright © 2017 Aleksandrs Muravjovs. All rights reserved.
//

#import "EvielasLibrary.h"


NSString *const kEviela = @"eViela";
NSString *const kNosaukums = @"nosaukums";
NSString *const kIespPielietojums = @"iespPielietojums";
NSString *const kIespIedarbiba = @"iespIedarbība";

@implementation EvielasLibrary

- (instancetype)init
{
    self = [super init];
    if (self) {
        
// E100 ... E180
        
        _library = @[@{kEviela : @"E100",
                           kNosaukums : @"Kurkumīns",
                           kIespPielietojums : @"Krāsviela",
                           kIespIedarbiba : @"Drošs"},
                         @{kEviela : @"E101",
                           kNosaukums : @"Riboflavīns",
                           kIespPielietojums : @"Nav informācijas.",
                           kIespIedarbiba : @"Drošs"},
                         @{kEviela : @"E102",
                           kNosaukums : @"Tartrazīns",
                           kIespPielietojums : @"Konditorejas izstrādājumi ,atspirdzinošie dzērieni, augļu sulas, marinēti dārzeņi, marcipāns, sausās zupas, siera cepumi, saldā kukurūza. \nLietošana citur: kosmētika, vilnas un zīda krāsa.",
                           kIespIedarbiba : @"Drošs"},
                         @{kEviela : @"E104",
                           kNosaukums : @"Hinolīna dzeltenais",
                           kIespPielietojums : @"Dzērieni, tehnoloģiski apstrādāti produkti. \nLietošana citur: kosmētiskās krāsas, lūpu krāsa, ziepes, zobu pasta, matu kopšanas līdzekļi, odekolons.",
                           kIespIedarbiba : @"Vairākās valstīs (ASV, Japāna) aizliegts. Var izraisīt hiperaktivitāti, astmu, nātreni."},
                         @{kEviela : @"E110",
                           kNosaukums : @"Saulrieta dzeltenais FCF",
                           kIespPielietojums : @"Augļu sulas, sausās zupas, konservētas zivis, konditorejas izstrādājumi, dzērienu pulveris, marcipāns, graudu produkti. \nLietošana citur: kosmētika, matu skalošanas līdzekļi.",
                           kIespIedarbiba : @"Vemšana, siena drudzis, astma, nātrene. Kancerogēns."},
                        @{kEviela : @"E120",
                          kNosaukums : @"Karmīnskābe, košenils",
                          kIespPielietojums : @"Pīrāgu pildījums, gaļas izstrādājumi, jogurts, cepti produkti, daži alkoholiskie dzērieni, sarkano ābolu biezenis. \nLietošana citur: kosmētika, šampūns, skropstu tuša, sarkanas krāsas acu dekoratīvā kosmētika.",
                          kIespIedarbiba : @"Anafilakse, astma, nātrene."},
                        @{kEviela : @"E123",
                          kNosaukums : @"Amarants",
                          kIespPielietojums : @"Atspirdzinošie dzērieni, upeņu produkti, sausais kūku maisījums, želejas kristāli, graudu produkti. \nLietošana citur: vaigu sārtums un cita kosmētika, lūpu krāsa.",
                          kIespIedarbiba : @"Astma, nātrene, hiperaktivitāte. Kancerogēns. Var ietekmēt aknas, nieres. Aizliegts Krievija, Norvēģija, ASV,Austrija, Somija."},
                        @{kEviela : @"E124",
                          kNosaukums : @"Košenila sarkanais, kumačs 4R",
                          kIespPielietojums : @"Tomātu zupa, biskvītkūkas sausais maisījums, deserta garnējums, želejas kristāli.",
                          kIespIedarbiba : @"hiperaktivitāte, astma, siena drudzis."},
                        @{kEviela : @"E127",
                          kNosaukums : @"Eritrozīns",
                          kIespPielietojums : @"Cukuroti ķirši, konservēti sarkanie ķirši, cepumi, desu apvalki, konservēti augļu kokteiļi. \nLietošana citur: vaigu sārtums, zobu pasta, medikamenti.",
                          kIespIedarbiba : @"Hiperaktivitāte, astma, nātrene, var iespaidot aknas, vairogdziedzeri, kuņģi, vairošanās funkciju, kuņģi."},
                        @{kEviela : @"E128",
                          kNosaukums : @"Sarkanais 2G",
                          kIespPielietojums : @"Desas, hamburgeru gaļa, vārīti gaļas produkti.",
                          kIespIedarbiba : @"Kuņģis, astma, hiperaktivitāte, nātrene, angioedēma."},
                        @{kEviela : @"E129",
                          kNosaukums : @"Alūra sarkanais AC",
                          kIespPielietojums : @"Želejas kristāli, sausais kūku maisījums, šokolādes cepumi, graudu produkti. \nLietošana citur: lūpu krāsa, kosmētika, ārstniecības līdzekļi.",
                          kIespIedarbiba : @"Alerģijas, astma, hiperaktivitāte, nātrene."},
                        @{kEviela : @"E131",
                          kNosaukums : @"Patentzilais V",
                          kIespPielietojums : @"Olas skotu gaumē. \nLietošana citur: diagnostikas krāsa medicīnā.",
                          kIespIedarbiba : @"Kancerogēns. Hiperaktivitāte, astma, jāizvairās pret aspirīnu jūtīgiem cilvēkiem. gremošanas slimību pazīmes, anafilakse"},
                        @{kEviela : @"E132",
                          kNosaukums : @"Indigotīns",
                          kIespPielietojums : @"Cepumi, saldējums, konditorejas izstrādājumi, pudelēs pildīti atspirdzinošie dzērieni, saldumi, maizes izstrādājumi. \nLietošana citur: tabletes un kapsulas, matu skalošanas līdzekļi.",
                          kIespIedarbiba : @"Hiperaktivitāte, astma, nav ieteicams bērniem."},
                        @{kEviela : @"E133",
                          kNosaukums : @"Briljantzilais FCF",
                          kIespPielietojums : @"Konservēti zaļie zirnīši, deserti, piena produkti, graudaugu produkti, želantīns, atspirdzinošie dzērieni. \nLietošana citur: dezodorants, matu krāsa, zobu pasta, kosmētika.",
                          kIespIedarbiba : @"Hiperaktivitāte, astma, jāizvairās pret aspirīnu jūtīgiem cilvēkiem. Nav ieteicam bērniem."},
                        @{kEviela : @"E140",
                         kNosaukums : @"Hlorofili, hlorofilīni",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Lietošanai uzturā nekaitīgs."},
                        @{kEviela : @"E141",
                         kNosaukums : @"Hlorofilu un hlorofilīnu vara kompleksie savienojumi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu"},
                        @{kEviela : @"E142",
                         kNosaukums : @"Zaļais S",
                         kIespPielietojums : @"Siera kūkas sausais maisījums, konservēti zirņi, piparmētru mērce.",
                         kIespIedarbiba : @"Akmeņogļu darvas krāsa. Astma, izsitumi uz ādas, bezmiegs, hiperaktivitāte."},
                        @{kEviela : @"E150a",
                         kNosaukums : @"Karamele",
                         kIespPielietojums : @"Kolas dzērieni, džemi, saldumi, šokolāde, tumšā maize, dzērieni.",
                         kIespIedarbiba : @"Gremošanas orgānu problēmas, ietekmē vairošanās funkcijas."},
                        @{kEviela : @"E150c",
                         kNosaukums : @"Amonija karamele",
                         kIespPielietojums : @"Cepumi, džemi, sojas mērce, šokolāde, tumšā maize, austeru mērce, marinēti dārzeņi.",
                         kIespIedarbiba : @"Hiperaktivitāte, var ietekmēt aknas,kuņģi. Testos uz dzīvniekiem izraisīja asins saindēšanos žurkām."},
                        @{kEviela : @"E150d",
                         kNosaukums : @"Amonija sulfīta karamele",
                         kIespPielietojums : @"Kolas dzērieni, porteris, konditorejas izstrādājumi, šokolāde.",
                         kIespIedarbiba : @"Hiperaktivitāte, pastiprināta zarnu darbība, žurkām izraisa asins saindēšanos. Aizdomīgs."},
                        @{kEviela : @"E151",
                         kNosaukums : @"Briljanta melnais BN, melnais PN",
                         kIespPielietojums : @"Dzeramais jogurts, upeņu kūkas sausais maisījums, brūnā mērce.",
                         kIespIedarbiba : @"Kancerogēns. Astma, ietekmē nieres, kuņģi, hiperaktivitāte, nav ieteicams bērniem"},
                       @{kEviela : @"E153",
                         kNosaukums : @"Augogle",
                         kIespPielietojums : @"Želejas konfektes, augļu sulas koncentrāts, lakrica, konditorejas izstrādājumi, džemi. \nLietošana citur: kosmētika.",
                         kIespIedarbiba : @"Nedaudz toksisks, ja apēd vai saskaras ar ādu."},
                       @{kEviela : @"E154",
                         kNosaukums : @"Brūnais FK",
                         kIespPielietojums : @"Kūpinātas un sālītas zivis, žāvētas siļķes, kartupeļu čipsi, vārīts šķiņķis.",
                         kIespIedarbiba : @"Astma, Alerģijas, var ietekmēt nieres, aknas, sirdi. Vajadzētu izvairīties cilvēkiem jūtīgiem pret aspirīnu. Nav ieteicams bērniem."},
                       @{kEviela : @"E155",
                         kNosaukums : @"Brūnais HT",
                         kIespPielietojums : @"Šokolādes cepumi, šokolādes kūkas sausais maisījums.",
                         kIespIedarbiba : @"Astma, alerģijas, nātrene, var ietekmēt nieres. nav ieteicam bērniem. Jāizvairās cilvēkiem jūtīgiem pret aspirīnu."},
                       @{kEviela : @"E160a",
                         kNosaukums : @"Karotīni",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E160b",
                         kNosaukums : @"Annato, biksīns, norbiksīns",
                         kIespPielietojums : @"Cepti produkti, brokastu pārslas, piena produkti, margarīns, samazināta tauku satura pastas. \nLietošana citur: ziepes, auduma krāsviela.",
                         kIespIedarbiba : @"Annato bērniem var izraisīt aizkaitināmību. Dunoņu galvā. Pazemināts asinsspiediens. Prurīts."},
                       @{kEviela : @"E160c",
                         kNosaukums : @"Paprikas ekstrakts, kapsantīns, kapsorubīns",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanas uzturā. Var būt labvēlīga ietekme uz veselību."},
                       @{kEviela : @"E160d",
                         kNosaukums : @"Likopēns",
                         kIespPielietojums : @"Zupas, jogurts, dzērieni, uzturvielu batoniņi.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā, var būt labvēlīga ietekme uz organismi. Var būt ģenētiski modificēts"},
                       @{kEviela : @"E160e",
                         kNosaukums : @"Beta - apo -8'- karotināls (C30)",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E160f",
                         kNosaukums : @"Beta - apo -8'- karotīnskābes etilesteris (C30)",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E161b",
                         kNosaukums : @"Luteīns",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā."},
                       @{kEviela : @"E161g",
                         kNosaukums : @"Kantaksantīns",
                         kIespPielietojums : @"Saldējums, zivju pirkstiņi, cepumi, konservi, mērces, marinēti dārzeņi.",
                         kIespIedarbiba : @"Ādas bālēšanas, nātrene, vistas aklums. Jūtīgums pret spilgtu gaismu."},
                       @{kEviela : @"E162",
                         kNosaukums : @"Biešu sarkanais, betanīns",
                         kIespPielietojums : @"Saldumi, lakrica, džemi, želejas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā, satur nitrātus. Nav ieteicams bērniem."},
                       @{kEviela : @"E163",
                         kNosaukums : @"Antocianīni",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā, var būt labvēlīga ietekme uz organismi."},
                       @{kEviela : @"E170",
                         kNosaukums : @"Kalcija karbonāti",
                         kIespPielietojums : @"-",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā."},
                       @{kEviela : @"E171",
                         kNosaukums : @"Titāna dioksīds",
                         kIespPielietojums : @"Košļājamā gumija, džems, želejas, ar cukuru pārklāti konditorejas izstrādājumi, saldumi.\nLietošana citur: dekoratīvais pūderis, sauļošanās aizsarglīdzeklis, pūders pēc vannas.",
                         kIespIedarbiba : @"Titāna dioksīda putekļu, ja to ieelpo, nesen ir klasificēti kā kancerogēns, iespējams, kancerogēna cilvēkam. Starptautiskā Vēža izpētes aģentūra (IARC). "},
                       @{kEviela : @"E172",
                         kNosaukums : @"Dzels oksīdi un hidroksīdi",
                         kIespPielietojums : @"Gaļas pastēte, kūku un desertu sausie maisījumi, lašu un garneļu pastēte.\nLietošana citur: dekoratīvais pūderis, dzīvnieku barība.",
                         kIespIedarbiba : @"Pārmērīgs daudzums rada risku saslimt ar daudzām slimībām. Dzelzs ir potenciāli toksiska."},
                       @{kEviela : @"E173",
                         kNosaukums : @"Alumīnijs",
                         kIespPielietojums : @"Kūku glazējums un citi.\nLietošana citur: pretsviedru līdzekļi, kosmētika, ēdiena gatavošanas katli un pannas, sudrabains pārklājums dražejām un tabletēm.",
                         kIespIedarbiba : @"Toksisks asinsrites orgāniem, dzimumorgāniem un nervu sistēmai. Ieēšana var saasināt nieru un plaušu slimības. ES parlaments pieņēmis lēmumu aizliegt  alumīniju saturošas piedevas. Ir konstatēta saistība ar Alcheimera slimību."},
                       @{kEviela : @"E174",
                         kNosaukums : @"Sudrabs",
                         kIespPielietojums : @"Ārējs kūku dekorējums, sudrab krāsas mandeles.\nLietošana citur: nagu laka, kosmētika.",
                         kIespIedarbiba : @"Uzkrājas audos, ietekmē nieres."},
                       @{kEviela : @"E175",
                         kNosaukums : @"Zelts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Neirotoksisks."},
                       @{kEviela : @"E180",
                         kNosaukums : @"Litorubīns BK",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nātrene, siena drudzis, kuņģa bojājumi, bezmiegs, hiperaktivitāte, astma."},
                     
// E200 ... E299
                     
                       @{kEviela : @"E200",
                         kNosaukums : @"Sorbīnskābe",
                         kIespPielietojums : @"Pīrāgu pildījumi, saldēta pica, siera kūka, siers, siera pasta, šokolādes sīrups.\nLietošana citur: zobu pasta, mutes skalošanas līdzekļi, kosmētika.",
                         kIespIedarbiba : @"Kontakta dermatīts, ādas apsārtums un kairinājums, astma, alerģijas."},
                       @{kEviela : @"E202",
                         kNosaukums : @"Kālija sorbāts",
                         kIespPielietojums : @"Šokolāde, siers, maize, cepti izstrādājumi, siera kūka, vīna ražošana.\nLietošana citur: cigaretes, kosmētika.",
                         kIespIedarbiba : @"Ādas kairinājums, uzvedības problēmas, alerģijas."},
                       @{kEviela : @"E203",
                         kNosaukums : @"Kalcija sorbāts",
                         kIespPielietojums : @"Siera kūka, mājas siers, maize, šokolādes sīrups, atspirdzinošie dzērieni, siera pasta.\nLietošana citur: kosmētika, ziedes.",
                         kIespIedarbiba : @"Ādas kairinājums, uzvedības problēmas, alerģijas. Astma."},
                       @{kEviela : @"E210",
                         kNosaukums : @"Benzoskābe",
                         kIespPielietojums : @"Saldējums, margarīns, vārīti atspirdzinošie dzērieni dzērieni, sidrs, uzkodu mērce, augļu sula, košļājamā gumija.\nLietošana citur: ādas tīrīšanas līdzeklis, kosmētika, matu skalošanas līdzeklis, medikamenti, smaržas.",
                         kIespIedarbiba : @"Ādas kairinājums, uzvedības problēmas, alerģijas. Astma, nātrene, var ietekmēt plaušas."},
                       @{kEviela : @"E211",
                         kNosaukums : @"Nātrija benzoāts",
                         kIespPielietojums : @"Var atrast kečupā, kaviārā, siera kūkā, pīrāgos, margarīnā, marinētos gurķīšos, ananāsu sulā, garnelēs, sojas mērcē, saldumos un galda olīvēs. Arī piena un gaļas produktos, konfektēs un dzērienos.\nLietošana citur: mutes dobuma ārstniecības līdzekļos, zobu pasta.",
                         kIespIedarbiba : @"Mutes un ādes kairinājums, hiperaktivitāte, anafilakse, kontakta dermatīts, astma, nātrene.  Savienojumā ar askorbīnskābi (E 300, vitamīns C) var veidot kancerogēnu bezolu."},
                       @{kEviela : @"E213",
                         kNosaukums : @"Kalcija benzoāts",
                         kIespPielietojums : @"Var būt košļājamā gumijā, augļu sulās, margarīnā un saldējumā, kā arī vārītos atspirdzinošos dzērienos.",
                         kIespIedarbiba : @"Anafilakse, hiperaktivitāte, ekzēma, uzvedības problēmas, astma, nātrene. Nav ieteicams bērniem."},
                       @{kEviela : @"E214",
                         kNosaukums : @"Etil-p-hidroksibenzoāts",
                         kIespPielietojums : @"Var būt saldējumā, sidrā, margarīnā, košļājamā gumijā, augļu sulas un vārītos atspirdzinošos dzērienos.\n Lietošana citur: kosmētikas produkti.",
                         kIespIedarbiba : @"Alerģijas, ādas apsārtums, nieze, uztūkums, anafilakse, astma, nātrene."},
                       @{kEviela : @"E215",
                         kNosaukums : @"Nātrija etil-p-hidroksibenzoāts",
                         kIespPielietojums : @"-",
                         kIespIedarbiba : @"Mutes nejūtīgums, alerģisks kontakta dermatīts, kuņģa kairinājums, astma."},
                       @{kEviela : @"E216",
                         kNosaukums : @"Propil-p-hidroksibenzoāts",
                         kIespPielietojums : @"Saldumi, cepti izstrādājumi, želejas konservi, dzērieni.\nLietošana citur: kosmētika, tonālais krēms, šampūns.",
                         kIespIedarbiba : @"Ādas kairinājums, uzpampums, alerģijas, astma, anafilakse."},
                       @{kEviela : @"E217",
                         kNosaukums : @"Nātrija propil-p-hidroksibenzoāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Kuņģa kairinājums, alerģisks kontakta dermatīts, nātrene, astma, mutes nejūtīgums."},
                       @{kEviela : @"E218",
                         kNosaukums : @"Metil-p-hidroksibenzoāts",
                         kIespPielietojums : @"Var būt konservos, želejās, ceptos izstrādājumos, augļu sulās un slātu mērcēs.\nLietošana citur: ādas  un matu kopšanas līdzekļi, kosmētika.",
                         kIespIedarbiba : @"Alerģijas, ādas apsārtum, nieze, uztūkums, anafilakse, astma, nātrene."},
                       @{kEviela : @"E219",
                         kNosaukums : @"Nātrija metil-p-hidroksibenzoāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Alerģijas, ādas apsārtums, nieze, uzpampums, anafilakse, astma, nātrene."},
                       @{kEviela : @"E220",
                         kNosaukums : @"Sēra dioksīds",
                         kIespPielietojums : @"Var atrasties alū, sidrā, vīnos, žāvētos augļos, etiķī, želatīnā un augļu sulā.",
                         kIespIedarbiba : @"Bronhu spazmas, astma, bronhu sažņaugšanās, pazemināts asinsspiediens, anafilakse, bronhīts, pārtikā noārda A un B vitamīnu"},
                       @{kEviela : @"E221",
                         kNosaukums : @"Nātrija sulfīts",
                         kIespPielietojums : @"Var būt saldētos ābolos, maraschino ķiršos, žāvētos un grieztos augļos, augļu pīrāga sausajos maisījumos.",
                         kIespIedarbiba : @"Astma, kuņģa kairinājums, izsitumi uz ādas, nelabums, caureja, pārtikā iznīcina B vitamīnu."},
                       @{kEviela : @"E222",
                         kNosaukums : @"Nātrija hidrogēnsulfīts",
                         kIespPielietojums : @"Var atrasties augļu sulās, tomātu pastā, žāvētos augļos, džemos un želejās.\nLietošana citur: mutes skalošanas līdzeklis, kārpu noņēmējs un matu krāsa.",
                         kIespIedarbiba : @"Bronhiālā astma, nātrene, ādas kairinājums, mutagēns."},
                       @{kEviela : @"E223",
                         kNosaukums : @"Nātrija metabisulfīts",
                         kIespPielietojums : @"Var atrasties žāvētos augļos, tomātu pastā, maizes un miltu izstrādājumos, maraschino ķiršos un želejās.\nLietošana citur; vannas putas un matu kopšanas līdzekļi, padušu dezodorants.",
                         kIespIedarbiba : @"Astma (dzīvībai bīstamas lēkmes), siena drudzis, nātrene, atopisks dermatīts."},
                       @{kEviela : @"E224",
                         kNosaukums : @"Kālija metabisulfīts",
                         kIespPielietojums : @"Var būt sierā un to saturošos produktos, kā arī mājas vīna gatavošanas komplektos.",
                         kIespIedarbiba : @"Anafilakse, Astma, nātrene, uzvedības problēmas, kuņģa kairinājum."},
                       @{kEviela : @"E226",
                         kNosaukums : @"Kalcija sulfīts",
                         kIespPielietojums : @"Konservēti dārzeņi un augļi.",
                         kIespIedarbiba : @"Astma, ādas un kuņģa kairinājums, var ietekmēt nieru, zarnu trakta un aknu darbību."},
                       @{kEviela : @"E227",
                         kNosaukums : @"Kalcija hidrogensulfīts",
                         kIespPielietojums : @"Var būt konservētos augļos un dārzeņos.",
                        kIespIedarbiba : @"Astma, kuņģa kairinājums, var ietekmēt aknas, nieres, plaušas, kuņģi."},
                       @{kEviela : @"E228",
                         kNosaukums : @"Kālija hidrogēnsulfīts",
                         kIespPielietojums : @"Var atrasties žāvētos augļos un maz-kaloriju džemā.",
                         kIespIedarbiba : @"Astma, ādas kairinājums, anafilakse, kuņģa kairinājums, hiperaktivitāte."},
                       @{kEviela : @"E230",
                         kNosaukums : @"Difenils, bifenils",
                         kIespPielietojums : @"Var atrasties marmelādē, citrusaugļu mizā. Lieto dažu augļu dezinficēšanai(atliekas var būt mizā), pārtikā, kas ietīta papīrā, kurš impregnēts ar difenilu.",
                         kIespIedarbiba : @"Var izraisīt tādas acu un deguna kairinājumu, vemšana, depresija, toksiska iedarbība uz nierēm, elpošanas orgāniem, asinsrites orgāniem un nervu sistēmu."},
                       @{kEviela : @"E231",
                         kNosaukums : @"Ortofenilfenols",
                         kIespPielietojums : @"Lieto pārtikas piedevu ražošanā.",
                         kIespIedarbiba : @"Kancerogēns. Krampji, nelabums,iedarbojas uz CNS un aknām."},
                       @{kEviela : @"E232",
                         kNosaukums : @"Nātrija o-fenilfenols",
                         kIespPielietojums : @"Lieto, lai apsmidzinātu augļu mizu. Var atrasties produktos, kas satur augļu mizu, marmelādē.\nLietošana citur: mazgāšanas līdzekļi, kosmētika.",
                         kIespIedarbiba : @"Kairina acis un ādu, vemšana, krampji."},
                       @{kEviela : @"E234",
                         kNosaukums : @"Nizīns",
                         kIespPielietojums : @"Var būt mannas un tapiokas pudiņos, konservētos dārzeņos un augļos, kausētā sierā.",
                         kIespIedarbiba : @"Eiropas Parlaments 2003. gadā ieteica nelietot, var izraisīt neuzņēmību pret antibiotikām"},
                       @{kEviela : @"E235",
                         kNosaukums : @"Natamicīns",
                         kIespPielietojums : @"Var būt siera mizā un vārītos, apstrādātos gaļas izstrādājumos.\nLietošana citur: zāles, ko lieto acu un acu plakstiņu sēnīšu infekciju ārstēšanā.",
                         kIespIedarbiba : @"Nelabums, vemšana, caureja, anoreksija, ādas kairinājums"},
                       @{kEviela : @"E239",
                         kNosaukums : @"Heksametilēntetramīns",
                         kIespPielietojums : @"Var būt provolones sierā.\nLietošana citur: kosmētika, lubrikantu eļļa.",
                         kIespIedarbiba : @"Aizdomas, ka ir kancerogēns. Dermatīts, kuņģa un zarnu trakta traucējumi, nieru bojājumi."},
                       @{kEviela : @"E242",
                         kNosaukums : @"Dimetildikarbonāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E249",
                         kNosaukums : @"Kālija nitrīts",
                         kIespPielietojums : @"Var būt sālītos, marinētos, kūpinātos, pārstrādātos un presētos gaļas izstrādājumos.",
                         kIespIedarbiba : @"Astma, nieru iekaisums, reibonis, galvassāpes. Nav atļauts uzturā bērniem līdz 6 mēnešu vecumam."},
                       @{kEviela : @"E251",
                         kNosaukums : @"Nātrija nitrāts",
                         kIespPielietojums : @"Var atrasties apstrādātos gaļas izstrādājumos.",
                         kIespIedarbiba : @"Vemšana, nelabuma sajūta, galvassāpes, var ietekmēt vairogdziedzeri, nav atļauts bērniem līdz 6. mēn. domātā pārtikā."},
                       @{kEviela : @"E252",
                         kNosaukums : @"Kālija nitrāts",
                         kIespPielietojums : @"Var būt kūpinātos, pārstrādātos gaļas izstrādājumos, šķiņķī  Prosciutto.\nLietošana citur: sērkociņi, tabaka.",
                         kIespIedarbiba : @"Astma, uzvedības problēmas, nieru iekaisums, galvassāpes, reibonis, nav atļauts bērniem līdz 6. mēn. domātā pārtikā."},
                       @{kEviela : @"E260",
                         kNosaukums : @"Etiķskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E261",
                         kNosaukums : @"Kālija acetāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E262",
                         kNosaukums : @"Nātrija acetāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E263",
                         kNosaukums : @"Kalcija acetāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E270",
                         kNosaukums : @"Pienskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Nav ieteicama bērniem līdz 3 mēn."},
                       @{kEviela : @"E280",
                         kNosaukums : @"Propionskābe",
                         kIespPielietojums : @"Var tikt lietots saldējumā, kausētos sieros, saldumos un ceptos izstrādājumos. Maizes rūpniecība.",
                         kIespIedarbiba : @"Migrēna, ādas kairinājums, galvassāpes."},
                       @{kEviela : @"E281",
                         kNosaukums : @"Nātrija propionāts",
                         kIespPielietojums : @"Tiek lietots kūku glazūrām, ceptos  un konditorejas izstrādājumos.\nLietošana citur: kosmētika, ādas sēnīšu infekciju apstrādei medicīnā.",
                         kIespIedarbiba : @"Ādas kairinājums, mācīšanās grūtības, astma, kuņģa kairinājums, galvassāpes."},
                       @{kEviela : @"E282",
                         kNosaukums : @"Kalcija propionāts",
                         kIespPielietojums : @"Var atrasties šokolādes produktos, putnu gaļas pildījumā, kausētā sierā un maizē.",
                         kIespIedarbiba : @"Astma, migrēna, mācīšanās grūtības, agresija, galvassāpes."},
                       @{kEviela : @"E283",
                         kNosaukums : @"Kālija propionāts",
                         kIespPielietojums : @"Var tikt lietots maizes, kūku, smalkmaizīšu, cepumu un citos miltu izstrādājumos.\nLietošana citur: kosmētika.",
                         kIespIedarbiba : @"Mācīšanās grūtības, galvassāpes, uzvedības problēmas."},
                       @{kEviela : @"E284",
                         kNosaukums : @"Borskābe",
                         kIespPielietojums : @"Tiek  izmantota sēnīšu slimību noteikšanai citrusaugļos. Var būt kaviārā.\nLietošana citur: pūderis bērniem,ziepes, krēms ādai ap acīm, mutes skalošanas līdzeklis, kosmētika.",
                         kIespIedarbiba : @"Toksiska iedarbība uz nierēm, asinsrites orgāniem, dzimumorgāniem, aknām un nervu sistēmu."},
                       @{kEviela : @"E285",
                         kNosaukums : @"Nātrija tetraborāts, boraks",
                         kIespPielietojums : @"Var atrasties no ASV importētos gaļas produktos.\nLietošana citur: tonālais krēms, skūšanās krēms.",
                         kIespIedarbiba : @"Patstāvīga saskare var izraisīt nieru mazspēju, krampjus. Reti lieto pārtikas produktos. Toksisks.Aizliegts lielākajā daļā valstu."},
                       @{kEviela : @"E290",
                         kNosaukums : @"Oglekļa dioksīds",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var samazināt auglību, teratogēns, toksisks nervu sistēmai, iespējams nekaitīgs lietošanai pārtikā."},
                       @{kEviela : @"E296",
                         kNosaukums : @"Abolskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E297",
                         kNosaukums : @"Fumārskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                     
// E300 ... E399
                     
                       @{kEviela : @"E300",
                         kNosaukums : @"Askorbīnskābe (C vitamīns)",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. C vitamīnam piemīt daudzveidīga, labvēlīga ietekme uz veselību."},
                       @{kEviela : @"E301",
                         kNosaukums : @"Nātrija askorbāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E302",
                         kNosaukums : @"Kalcija askorbāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā."},
                       @{kEviela : @"E304",
                         kNosaukums : @"Taukskābju, askorbīnskābes esteri",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E306",
                         kNosaukums : @"Tokoferoli",
                         kIespPielietojums : @"Piena produkti, salātu eļļa, margarīns.\nLietošana citur: produkti bērniem, dezodorants, uztura bagātinātāji.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E307",
                         kNosaukums : @"Alfa-tokoferols",
                         kIespPielietojums : @"Var būt margarīnā, baltajos rīsos, baltajos miltos un baltmaizē.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E308",
                        kNosaukums : @"Gamma-tokoferols",
                         kIespPielietojums : @"Var tikt lietots slātu eļļā, piena produktos un margarīnā.",
                         kIespIedarbiba : @"E vitamīns. Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E309",
                         kNosaukums : @"Delta-tokoferols",
                         kIespPielietojums : @"Var būt margarīnā, salātu eļļā, piena produktos.",
                         kIespIedarbiba : @"E vitamīns. Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E310",
                         kNosaukums : @"Propilgallāts",
                         kIespPielietojums : @"Var tikt lietots piena produktos, pārtikas taukos un eļļā, margarīnā, salātu eļļā, košļājamā gumijā un zemesriekstu sviestā.\nLietošana citur: kosmētiskie krēmi un losjoni.",
                         kIespIedarbiba : @"Dermatīts, kuņģa kairinājums, nav atļauts pārtikā zīdaiņiem un maziem bērniem."},
                       @{kEviela : @"E311",
                         kNosaukums : @"Oktigallāts",
                         kIespPielietojums : @"Var tikt lietots margarīnā un pārtikas taukos un eļļā.",
                         kIespIedarbiba : @"Apēdot vidēji toksisks, kuņģa kairinājums."},
                       @{kEviela : @"E312",
                         kNosaukums : @"Dodecilgallāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nav ieteicams bērniem, dermatīts, alerģijas, kuņģa kairinājums."},
                       @{kEviela : @"E315",
                         kNosaukums : @"Eritorbīnskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Dažiem cilvēkiem var izraisīt alerģiskas reakcijas."},
                       @{kEviela : @"E316",
                         kNosaukums : @"Nātrija eritorbāts",
                         kIespPielietojums : @"Nav informācijas.",
                        kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. mutagēna iedarbība nav pārbaudīta."},
                       @{kEviela : @"E320",
                         kNosaukums : @"Butilēts hidroksianizols",
                         kIespPielietojums : @"Var tikt lietots košļājamā gumijā, pārtikas taukos un eļļās, ātri pagatavojamās kartupeļu biezputrās, saldējumā, margarīnā un gaļas izstrādājumos.\nLietošana citur: kosmētika.",
                         kIespIedarbiba : @"Kancerogēns. Galvassāpes, nogurums, astma. Var ietekmēt nieres, aknas, dzimumorgānus. Nav ieteicam bērniem. Nātrene, miegainība, hormonu līdzsvara sagraušana. Naftas derivāts, dažās valstīs aizliegts."},
                       @{kEviela : @"E321",
                         kNosaukums : @"Butilēts hidroksitoluols",
                         kIespPielietojums : @"Var tikt lietots pārtikas taukos un eļļās, zivju produktos, alus un iesala dzērienos, polietilēna plēve pārtikas produktu iesaiņošanai, košļājamā gumija, sausās brokastu pārslas.\nLietošana citur: eļļa un losjons bērniem, skūšanās krēms, acu kontūrzīmulis, lūpu krāsa, reaktīvo lidmašīnu degviela.",
                         kIespIedarbiba : @"Hroniska nātrene, dermatīts, nogurums, astma, agresīva uzvešanās, bronhu spazmas. Nav ieteicams bērniem."},
                       @{kEviela : @"E322",
                         kNosaukums : @"Lecitīni",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E325",
                         kNosaukums : @"Nātrija laktāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E326",
                         kNosaukums : @"Kālija laktāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E327",
                         kNosaukums : @"Kalcija laktāts",
                         kIespPielietojums : @"Var būt konditorejas izstrādājumos, iebiezinātā pienā, cepamajā pulverī, konservētās diedzētās pupiņās.\nLietošana citur: zobu kopšanas līdzekļi, barība dzīvniekiem.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā, var radīt sirds, kuņģa un zarnu darbības traucējumus."},
                       @{kEviela : @"E330",
                         kNosaukums : @"Citronskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Var izraisīt alerģisku reakciju cilvēkiem, kuri reaģē uz mononātrija glutamātu."},
                       @{kEviela : @"E331",
                         kNosaukums : @"Nātrija citrāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var izraisīt dažu zāļu izdalīšanos ar urīnu, padarot tās vai nu mazāk iedarbīgas, vai iedarbīgākas."},
                       @{kEviela : @"E332",
                         kNosaukums : @"Kālija citrāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var izraisīt alerģisku reakciju cilvēkiem, kuri reaģē uz mononātrija glutamātu."},
                       @{kEviela : @"E333",
                         kNosaukums : @"Kālija citrāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var izraisīt alerģisku reakciju cilvēkiem, kuri reaģē uz mononātrija glutamātu."},
                       @{kEviela : @"E334",
                         kNosaukums : @"Vīnskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā."},
                       @{kEviela : @"E335",
                         kNosaukums : @"Nātrija tartrāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E336",
                         kNosaukums : @"Kālija tartrāti",
                         kIespPielietojums : @"Var tik izmantoti konditorejas izstrādājumos, augļu želejā, cepamajā pulverī, augļu sulās un dzērienos.\nLietošana citur: depilācijas līdzekļi, matu skalošanas līdzekļi, nagu balinātājs.",
                         kIespIedarbiba : @"Cilvēkiem, kuriem pavājināta nieru vai aknu darbība vajadzētu izvairīties. Augsts asinsspiediens."},
                       @{kEviela : @"E337",
                         kNosaukums : @"Kālija nātrija tartrāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E338",
                         kNosaukums : @"Fosforskābe",
                         kIespPielietojums : @"Var tikt izmantota siera izstrādājumos, saldumos, želejās un atspirdzinošos dzērienos.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā. Pārmērīgs daudzums var izraisīt zobu eroziju."},
                       @{kEviela : @"E339",
                         kNosaukums : @"Nātrija fosfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E340",
                         kNosaukums : @"Kālija fosfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E341",
                         kNosaukums : @"Kalcija fosfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E343",
                         kNosaukums : @"Magnija fosfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E350",
                         kNosaukums : @"Nātrija malāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E351",
                         kNosaukums : @"Kālija malāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E352",
                         kNosaukums : @"Kalcija malāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E353",
                         kNosaukums : @"Metavīnskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nelielā daudzumā nekaitīga."},
                       @{kEviela : @"E354",
                         kNosaukums : @"Kalcija tartrāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E355",
                         kNosaukums : @"Adipīnskābe",
                         kIespPielietojums : @"Var tikt lietota ceptos izstrādājumos, saldumos, kausētā sierā , eļļās un dzērienos.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā. Žurkām toksiska, pat nāvējoša."},
                       @{kEviela : @"E356",
                         kNosaukums : @"Nātrija adipināts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E357",
                         kNosaukums : @"Kālija adipināts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E363",
                         kNosaukums : @"Dzintarskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Pārmērīgs daudzums var izraisīt vemšanu un caureju."},
                       @{kEviela : @"E380",
                         kNosaukums : @"Triamonija citrāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var veicināt alerģiskus simptomus cilvēkiem, kuri reaģē uz mononātrija glutamātu."},
                       @{kEviela : @"E385",
                         kNosaukums : @"Kalcija dinātrija etilēndiamīntetraacetāts",
                         kIespPielietojums : @"Var tikt lietots šķīstošās tējās, margarīnā, dažādās mērcēs, atspirdzinošos dzērienos un alū, gaišajā alū un sviestmaižu pastā.\nLietošana citur: medicīnā saindēšanās gadījumos ar smagajiem metāliem.",
                         kIespIedarbiba : @"Asinis urīnā, zarnu darbības traucējumi, nieru bojājumi, hromosomu bojājumi, muskuļu krampji. Dažās valstīs aizliegts."},
                     
// E400 ... E499
                     
                       @{kEviela : @"E400",
                         kNosaukums : @"Algīnskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Neliels daudzums nekaitīgs."},
                       @{kEviela : @"E401",
                         kNosaukums : @"Nātrija algināts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var būt labvēlīga ietekme uz veselību."},
                       @{kEviela : @"E402",
                         kNosaukums : @"Kālija algināts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Labvēlīga ietekme uz organismu."},
                       @{kEviela : @"E403",
                         kNosaukums : @"Amonija algināts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var būt labvēlīga ietekme uz veselību."},
                       @{kEviela : @"E404",
                         kNosaukums : @"Kalcija algināts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var būt labvēlīga ietekme uz veselību."},
                      @{kEviela : @"E405",
                         kNosaukums : @"Propān-1, 2-diola algināts",
                         kIespPielietojums : @"Var būt augļu šerbetā, salātu mērcēs, saldējumā un saldētā olu krēmā.\nLietošana citur: kosmētikā.",
                         kIespIedarbiba : @"Palēnināta augšana, var izraisīt alerģiskas reakcijas."},
                       @{kEviela : @"E406",
                         kNosaukums : @"Agars",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E407",
                         kNosaukums : @"Karagināns",
                         kIespPielietojums : @"Var tikt lietots saldējumā, konditorejas izstrādājumos, cepumos, šokolādes produktos, smalkmaizītēs un deserta maisījumos.\nLietošana citur: zobu pasta, klepus zāles, kosmēttika.",
                         kIespIedarbiba : @"Var ietekmēt gremošanas orgānus, kuņģi, čūlains stomatīts. Nav ieteicams bērniem."},
                       @{kEviela : @"E407a",
                         kNosaukums : @"Abstrādātas jūraszāles (Eucheuma)",
                         kIespPielietojums : @"VTehnoloģiski apstrādāti produkti.",
                         kIespIedarbiba : @"Pastāv šaubas par šīs piedevas nekaitīgumu."},
                       @{kEviela : @"E410",
                         kNosaukums : @"Baltās akācijas sveķi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E412",
                         kNosaukums : @"Guāra sveķi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E413",
                         kNosaukums : @"Tragakans",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā. Var izraisīt nelabvēlīgas reakcijas."},
                       @{kEviela : @"E414",
                         kNosaukums : @"Akāciju sveķi; gumiarābiks",
                         kIespPielietojums : @"Var tikt izmantoti  glazūrā, atspirdzinošos dzērienos, konditorejas izstrādājumos, želejā, košļājamā gumijā.\nLietošana citur: matu kopšanas līdzekļi kosmētika un medikamenti.",
                         kIespIedarbiba : @"Mutes gļotādas bojājumi, izsitumi uz ādas, siena drudzis."},
                       @{kEviela : @"E415",
                         kNosaukums : @"Ksantāna sveķi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E416",
                         kNosaukums : @"Karaja sveķi",
                         kIespPielietojums : @"Var tikt izmantoti ceptos izstrādājumos, saldējumā, saldētos piena produktos, saldumos, ledenēs.\nLietošana citur: losjons matu fiksācijai, matu laka, skūšanās krēms, zobu pasta, losjons rokām.",
                         kIespIedarbiba : @"Dermatīts, samazina uzturvielu uzsūkšanos, siena drudzis."},
                       @{kEviela : @"E417",
                         kNosaukums : @"Tara sveķi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E418",
                         kNosaukums : @"Želena sveķi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E420",
                         kNosaukums : @"Sorbīts; sorbīta sīrups",
                         kIespPielietojums : @"Var būt sūkājamās konfektēs uz kociņa, šokolādē, košļājamā gumijā, konditorejas izstrādājumi, žāvēti augļi.\nLietošana citur: šampūns, mutes skalojamais līdzeklis, matu aerosols, kosmētika, zobu pasta, antifrīzs.",
                         kIespIedarbiba : @"Kuņģa un zarnu trakta darbības traucējumi, vēdera uzpūšanās, katarakta, caureja, zarnu krampji. Iekļauts NIH bīstamo vielu sarakstā."},
                       @{kEviela : @"E421",
                         kNosaukums : @"Mannīts",
                         kIespPielietojums : @"Var būt pārtikā ar modificētiem ogļhidrātiem un samazinātu kaloriju daudzumu, saldumi, džemi, želejas un košļājamā gumija.\nLietošana citur: matu kopšanas līdzekļi krēms rokām.",
                         kIespIedarbiba : @"Vemšana, caureja, nātrene. Nav ieteicams bērniem un diabētiķiem. Nieru disfunkcija, anafilakse."},
                       @{kEviela : @"E422",
                         kNosaukums : @"Glicerīns",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E425",
                         kNosaukums : @"Konjac",
                         kIespPielietojums : @"Var būt sūkājamās konfektēs, džemā, majonēzē,zupā, gaļas mērcēs.",
                         kIespIedarbiba : @"Caureja, vēdargraizes, uzturvielu sagraušana."},
                       @{kEviela : @"E431",
                         kNosaukums : @"Polioksietilēna stearāts (40)",
                         kIespPielietojums : @"Var būt tehnoloģiski apstrādātos produktos un saldētos desertos.\nLietošana citur: krēms rokām un losjons.",
                         kIespIedarbiba : @"Var veicināt vēzi izraisošu piedevu uzsūkšanos."},
                       @{kEviela : @"E432",
                         kNosaukums : @"Polioksietilēna sorbitāna monolaurāts; polisorbāts 20",
                         kIespPielietojums : @"Lietošana citur: kosmētiskais krēms un losjons.",
                         kIespIedarbiba : @"Var saturēt kaitīgu ķīmisku vielu atliekas."},
                       @{kEviela : @"E433",
                         kNosaukums : @"Polioksietilēna sorbitāna monooleāts; polisorbāts 80",
                         kIespPielietojums : @"Var būt saldētā ogu krēmā, majonēzē, šerbertā, marinētos dārzeņos, saldējumā un glazūrās.\nLietošana citur: vitamīnu un minerālvielu piedevas.",
                         kIespIedarbiba : @"Līdzīgs indīgai vielai - 1,4-dioksānam, ko pazīst, kā vēža izraisītāju dzīvniekiem."},
                       @{kEviela : @"E434",
                         kNosaukums : @"Polioksietilēna sorbitāna monopalmiāts; polisorbāts 40",
                         kIespPielietojums : @"Var būt putukrējumā, konditorejas izstrādājumos, zupās un dzērienos.",
                         kIespIedarbiba : @"Var saturēt kaitīgu ķīmisku vielu atliekas."},
                       @{kEviela : @"E435",
                         kNosaukums : @"Polioksietilēna sorbitāna monostearāts; polisorbāts 60",
                         kIespPielietojums : @"Var atrasties kūku sausajos maisījumos, kūkās, glazūrā, dzērienu sausajos maisījumos un konditorejas izstrādājumos.",
                         kIespIedarbiba : @"Līdzīgs indīgai vielai 1,4-dioksānam, ko pazīst, kā vēža izraisītāju dzīvniekiem."},
                       @{kEviela : @"E436",
                         kNosaukums : @"Polioksietilēna sorbitāna tristearāts; polisorbāts 65",
                         kIespPielietojums : @"Var būt saldētā olu krēmā, saldējumā, sausos kūku maisījumos, glazūrā un pildījumos.",
                         kIespIedarbiba : @"Var saturēt kaitīgu ķīmisku vielu atliekas."},
                       @{kEviela : @"E440",
                         kNosaukums : @"Pektīni",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var būt labvēlīga ietekme uz veselību."},
                       @{kEviela : @"E442",
                         kNosaukums : @"Amonija fosfatīdi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E444",
                         kNosaukums : @"Saharozes acetāta izobutirāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E445",
                         kNosaukums : @"Polofonija glicerīna esteri",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nav datu par nekaitīgumu."},
                       @{kEviela : @"E450",
                         kNosaukums : @"Difosfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E451",
                         kNosaukums : @"Trifosfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E452",
                         kNosaukums : @"Polifosfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E459",
                         kNosaukums : @"Beta-ciklodekstrīns",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E460",
                         kNosaukums : @"Celuloze",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E461",
                         kNosaukums : @"Metilceluloze",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E463",
                         kNosaukums : @"Hidroksipropilceluloze",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E464",
                         kNosaukums : @"Hidroksipropilmetilceluloze",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E465",
                         kNosaukums : @"Etilmetilceluloze",
                         kIespPielietojums : @"Var atrasties augu taukos, putotos garnējumos, zema tauku satura krējums, saldējuma aizstājējos.\nLietošana citur: tabaka, caurejas līdzeklis.",
                         kIespIedarbiba : @"Var izraisīt gremošanas problēmas, kuņģa un zarnu trakta darbības traucējumus, caureju."},
                       @{kEviela : @"E466",
                         kNosaukums : @"Karboksimetilceluloze, karboksimetilcelulozes nātrija sālse",
                         kIespPielietojums : @"Var būt zīdaiņu pārtikā, m;ajas sierā, siera pastā, konditorejas izstrādājumos un saldējumā.\nLietošana citur: krēms rokām, matu fiksācijas līdzekļi, medikamenti, tabaka, zāles pret caureju.",
                         kIespIedarbiba : @"Liels daudzums var izraisīt caureju, vēdera krampjus. Dzīvnieku testos izraisīja vēzi un citus audzējus. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E468",
                         kNosaukums : @"Šķeršūtās karboksimetilcelulozes nātrija sāls",
                         kIespPielietojums : @"Var būt saldinātājos.",
                         kIespIedarbiba : @"Var būt ģenētiski modificēts. Caureja."},
                       @{kEviela : @"E469",
                         kNosaukums : @"Fermentatīvi hidrolizēta karboksimetilceluloze",
                         kIespPielietojums : @"Var būt treknos gaļas izstrādājumos, saldējumā un zupās.",
                         kIespIedarbiba : @"Izraisa vēzi dzīvniekiem, caureja, zarnu trakta darbības traucējumi."},
                       @{kEviela : @"E470a",
                         kNosaukums : @"Taukskābju nātrija, kālija, kalcija sāļi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E470b",
                         kNosaukums : @"Taukskābju nātrija, kālija, kalcija sāļi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E471",
                         kNosaukums : @"Taukskābju monoglicerīdi un diglicerīdi",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E472a",
                         kNosaukums : @"Taukskābju monoglicerīdu un diglicerīdu etiķskābes esteri",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E472b",
                         kNosaukums : @"Taukskābju monoglicerīdu un diglicerīdu pienskābes esteri",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E473",
                         kNosaukums : @"Taukskābju saharozes esteri",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E474",
                         kNosaukums : @"Saharozes glicerīdi.",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E475",
                         kNosaukums : @"Taukskābju poliglicerīna esteri",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E476",
                         kNosaukums : @"Poliglicerīna poliricinolāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E477",
                         kNosaukums : @"Taukskābju propān-1, 2-diola esteri",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var būt ģenētiski modificēts. Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E481",
                         kNosaukums : @"Nātrija stearoil-2-laktilāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Var būt ģenētiski modificēts."},
                       @{kEviela : @"E482",
                         kNosaukums : @"Kalcija stearoil-2-laktilāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E483",
                         kNosaukums : @"Steariltartrāts",
                         kIespPielietojums : @"Var būt dažādās mīklās.",
                         kIespIedarbiba : @"Dažās valstīs aizliegts. Pastāv aizdomas par kancerogēnu."},
                       @{kEviela : @"E491",
                         kNosaukums : @"Sorbitāna monostearāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Var būt ģenētiski modificēts.  Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E492",
                         kNosaukums : @"Sorbitāna tristearāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā.  Var būt ģenētiski modificēts."},
                       @{kEviela : @"E493",
                         kNosaukums : @"Sorbitāna monolaurāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E494",
                         kNosaukums : @"Sorbitāna monooleāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E495",
                         kNosaukums : @"Sorbitāna monopalmiāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                     
// E500 ... E599
                     
                       @{kEviela : @"E500",
                         kNosaukums : @"Nātrija karbonāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Liels daudzums var izraisīt asiņošanu kuņģī un zarnu traktā."},
                       @{kEviela : @"E501",
                         kNosaukums : @"Kālija karbonāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā. Acu kairinājums, augšējo elpošanas ceļu iekaisums."},
                       @{kEviela : @"E503",
                         kNosaukums : @"Amonija karbonāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E504",
                         kNosaukums : @"Magnija karbonāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E507",
                         kNosaukums : @"Sālsskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E508",
                         kNosaukums : @"Kālija hlorīds",
                         kIespPielietojums : @"Var būt pārtikā un sālī ar samazinātu nātrija saturu.\nLietošana citur: kosmētika, minerālmēsli.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā nelielā daudzumā. Nav ieteicams bērniem. Toksisks aknām, asinsrites orgāniem, elpošanas orgāniem."},
                       @{kEviela : @"E509",
                         kNosaukums : @"Kalcija hlorīds",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā.Tahikardija, ādas un gļotādas kairinājums."},
                       @{kEviela : @"E511",
                         kNosaukums : @"Magnija hlorīds",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E512",
                         kNosaukums : @"Alvas hlorīds",
                         kIespPielietojums : @"Var būt konservētās augļu sulās, konservētos sparģeļos un konservētos atspirdzinošos dzērienos.\nLietošana citur: krāsu ražošana.",
                         kIespIedarbiba : @"Neliels toksiskums, var kairināt gļotādu,ādu."},
                       @{kEviela : @"E513",
                         kNosaukums : @"Sērskābe",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Izmanto cietes pārveidošanai. Droša, izmantojot kā pārtikas piedevu. ĻOTI BĪSTAMA KONCENTRĒTĀ VEIDĀ."},
                       @{kEviela : @"E514",
                         kNosaukums : @"Nātrija sulfāti",
                         kIespPielietojums : @"Var būt tuncī, cepumos un košļājamās gumijas bāzē.\nLietošana citur: papīra  un stikla ražošana, krāsu, ziepju un mazgāšanas līdzekļu ražošana.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā. Ādas kairinājums, cilvēkiem ar nieru vai aknu darbības traucējumiem vajadzētu izvairīties."},
                       @{kEviela : @"E515",
                         kNosaukums : @"Kālija sulfāti",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E516",
                         kNosaukums : @"Kalcija sulfāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E517",
                         kNosaukums : @"Amonija sulfāts",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E520",
                         kNosaukums : @"Alumīnija sulfāts",
                         kIespPielietojums : @"Var būt saldi marinētos dārzeņos, marinētu dārzeņu piedevās un cietes modificētājā.\nLietošana citur: pretsviedru līdzeklis, iesaiņošanas materiāli, dezodorants, ādas atsvaidzinātāji.",
                         kIespIedarbiba : @"Vidēji toksisks, alerģija, var ietekmēt dzimstību."},
                       @{kEviela : @"E521",
                         kNosaukums : @"Alumīnija nātrija sulfāts",
                         kIespPielietojums : @"Var būt miltos, balinātos miltos un graudu produktos.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā.Pēc saskares iespējami izsitumi uz ādas."},
                       @{kEviela : @"E522",
                         kNosaukums : @"Alumīnija kālija sulfāts",
                         kIespPielietojums : @"Var būt miltos, sierā un graudu produktos.\nLietošana citur: ietinamais papīrs, pēcskūšanās losjons.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā. Lielā daudzumā var būt gļotādas apdegumi."},
                       @{kEviela : @"E523",
                         kNosaukums : @"Alumīnija amonija sulfāts",
                         kIespPielietojums : @"Var atrasties cepamajā pulverī, graudu un miltu pārstrādes produkcijā.\nLietošana citur: dzeramā ūdens attīrīšana, augu līme, ugunsdrošības līdzekļi.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā. Lielā daudzumā var būt gļotādas apdegumi, vemšana."},
                       @{kEviela : @"E524",
                         kNosaukums : @"Nātrija hidroksīds",
                         kIespPielietojums : @"Nav informācijas.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā."},
                       @{kEviela : @"E525",
                         kNosaukums : @"Kālija hidroksīds",
                         kIespPielietojums : @"Var būt kakao produktos.",
                         kIespIedarbiba : @"Nelielā daudzumā uzskata par nekaitīgu lietošanai uzturā. Nagu bojājumi, ādas kairinājums."},
    
                     
                     
                     
                     
                     
                     
                     
                     
                     
                    
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
        

                     ];
        
        
        
    }
    return self;
}


@end
